//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopClothes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BILL
    {
        public BILL()
        {
            this.DE_BILL = new HashSet<DE_BILL>();
        }
    
        public int ID { get; set; }
        public int IDORDER { get; set; }
        public int ORI_PRICE { get; set; }
        public double TOTALMONEY { get; set; }
        public System.DateTime DATETIME { get; set; }
        public string NOTE { get; set; }
        public Nullable<int> CREATEBY { get; set; }
        public System.DateTime CREATEAT { get; set; }
        public Nullable<int> UPDATEBY { get; set; }
        public Nullable<System.DateTime> UPDATEAT { get; set; }
        public int METHODS { get; set; }
    
        public virtual ORDER ORDER { get; set; }
        public virtual ICollection<DE_BILL> DE_BILL { get; set; }
    }
}
