//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopClothes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COLOR
    {
        public COLOR()
        {
            this.DETAIL_PRODUCT = new HashSet<DETAIL_PRODUCT>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
    
        public virtual ICollection<DETAIL_PRODUCT> DETAIL_PRODUCT { get; set; }
    }
}
