//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopClothes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMAGES
    {
        public IMAGES()
        {
            this.PRODUCTS = new HashSet<PRODUCT>();
        }
    
        public int ID { get; set; }
        public string IMAGE { get; set; }
    
        public virtual ICollection<PRODUCT> PRODUCTS { get; set; }
    }
}
