//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopClothes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        public PRODUCT()
        {
            this.DE_ORDER = new HashSet<DE_ORDER>();
            this.DETAIL_PRODUCT = new HashSet<DETAIL_PRODUCT>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public int PRICE { get; set; }
        public int ORI_PRICE { get; set; }
        public int USD_PRICE { get; set; }
        public int HOTPRODUCT { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> CREATEBY { get; set; }
        public Nullable<System.DateTime> CREATEAT { get; set; }
        public Nullable<int> UPDATEBY { get; set; }
        public Nullable<System.DateTime> UPDATEAT { get; set; }
        public Nullable<int> IMAGE { get; set; }
        public int COMPANY { get; set; }
        public Nullable<int> IDCATEGORY { get; set; }
        public int SEX { get; set; }
    
        public virtual CATEGORIES CATEGORIES { get; set; }
        public virtual COMPANIES COMPANIES { get; set; }
        public virtual ICollection<DE_ORDER> DE_ORDER { get; set; }
        public virtual ICollection<DETAIL_PRODUCT> DETAIL_PRODUCT { get; set; }
        public virtual IMAGES IMAGES { get; set; }
        public virtual SEX SEX1 { get; set; }
    }
}
